// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fggjupkatzgnkyzktuhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZ2p1cGthdHpnbmt5emt0dWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTg4NjcsImV4cCI6MjA2NTkzNDg2N30.5zQqGrfVuL9DJOpEM_63Hq_8q-YDI2olUcbZAA_Qi8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);